### ISSUE TITLE
sqlite error

### ISSUE THREAD

**Issue by Sagarkanojia5774** [Linuxndroid/WhatsApp-Viewer#2]
### WhatsApp Database Exporter ###
[+] Reading Database
Traceback (most recent call last):
  File "/home/kali/WhatsApp-Viewer/main.py", line 113, in <module>
    main()
  File "/home/kali/WhatsApp-Viewer/main.py", line 98, in main
    contacts = query_contacts(config["input"].get("wa_path"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/WhatsApp-Viewer/main.py", line 79, in query_contacts
    con = sqlite3.connect(db_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

**Comment by afarhansib** [comment]
same issue

**Comment by anonymousthehiddenuser** [comment]
just provide your db file path in "config.cfg"

**Comment by Linuxndroid** [comment]
Please use now Updated version and pre exe file
